#!/usr/local/bin/bash

# A work in progress for setting up basic environment on Mac.

should_quit() {
	if [ "${1,,}" = "q" ] || [ "${1,,}" = "quit" ]
	then
		echo "Quitting..."
		exit 0
	fi
}

echo "WARNING: Are you sure you want to setup environment? This will overwrite existing files."
read -p "Enter 'q' or 'quit' to stop " answer
should_quit $answer

echo "Setting up bash_profile"
touch ~/.bash_profile
echo "alias l='ls -GAF'" >> ~/.bash_profile
echo "alias ll='ls -FlAG'" >> ~/.bash_profile
echo "alias subl='open -a Sublime\ Text'" >> ~/.bash_profile
echo "alias code='open -a Visual\ Studio\ Code'" >> ~/.bash_profile
echo "alias charm='open -a PyCharm'" >> ~/.bash_profile

echo "# Setting the bash prompt" >> ~/.bash_profile
echo "export PS1='\[\e[32m\]\W \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ '" >> ~/.bash_profile
source ~/.bash_profile

# WIP...